csip: Fix java.lang.ArrayIndexOutOfBoundsException issue in isConnected
In current state machine design, there could be timing issue issue to cause
java.lang.ArrayIndexOutOfBoundsException: index=-1, when state transition exit
one state to enter another state.
at this timing, the mStateStackTopIndex value of mStateStack be set to -1.

Fix: check mCurrentConnectionState maintained in csip state machine to avoid
calling getCurrentState to cause AndroidRuntime exception.

CRs-Fixed: 3886484
Change-Id: I7110890e1cfc18e21c582f89e3fc74e5ea9a4db1